##################################################################################################################
# SVclone configuration for the VISOR chr1-2 replicate benchmark.
##################################################################################################################

[BamParameters]
# Infer read and fragment lengths from each BAM.
read_len: -1
insert_mean: -1
insert_std: -1
mean_cov: 50
max_cn: 10

[SVannotateParameters]
use_dir: FALSE
sv_class_field: none
trust_sc_position: False

[SVcountParameters]
threshold: 6
norm_overlap: 10
sc_len: 10

[SVclasses]
inversion_class: INV
deletion_class: DEL
dna_gain_class: DUP,INTDUP
dna_loss_class: DEL,INV,TRX
itrx_class: INTRX

[SocratesOpts]
pos1: C1_anchor
dir1: C1_anchor_dir
pos2: C1_realign
dir2: C1_realign_dir
avg_mapq1: C1_avg_realign_mapq
avg_mapq2: C2_avg_realign_mapq
repeat1: repeat1
repeat2: repeat2
filter_repeats: Satellite,Simple_repeat
min_mapq: 20

[DebugParameters]
write_anomalous: False

[FilterParameters]
neutral: False
size_filter: -1
min_dep: 2
min_span: 1
min_split: 1
filter_outliers: False
filter_chroms: False
filter_subclonal_cnvs: False
strict_cnv_filt: True
germline_threshold: 10
support_adjust_factor: 0
sv_offset: 100000

[ValidationParameters]
chroms: 1,2

[ClusterParameters]
threads: 8
repeat: 5
n_iter: 1000
clus_limit: 3
adjusted: True
male: True
sv_to_sim: 0
